/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState, memo, useCallback } from "react";
import { SkeletonUtils } from "three-stdlib";
import { useGrid } from "../hooks/useGrid";
import { socket, userAtom } from "./SocketManager";

import * as THREE from "three";
import { motion } from "framer-motion-3d";

const MOVEMENT_SPEED = 4;

// Distance threshold (squared) for rendering avatars — avatars beyond this are culled
const RENDER_DISTANCE_SQ = 30 * 30;
// Closer distance for showing HTML overlays (chat bubbles, action indicators)
const HTML_DISTANCE_SQ = 18 * 18;

// Reusable vector to avoid allocations in the hot loop
const _direction = new THREE.Vector3();

export const Avatar = memo(function Avatar({
  id,
  avatarUrl = "https://models.readyplayer.me/64f0265b1db75f90dcfd9e2c.glb",
  name = "Player",
  isBot = false,
  ...props
}) {
  const [chatMessage, setChatMessage] = useState("");
  const [actionStatus, setActionStatus] = useState(null); // { action, detail }
  const position = useMemo(() => props.position, []);
  // Use refs for culling state to avoid re-renders from useFrame distance checks
  const isNearbyRef = useRef(true);
  const showHtmlRef = useRef(true);
  const [, forceUpdate] = useState(0);

  const avatar = useRef();
  const pathRef = useRef([]);
  const pathIndexRef = useRef(0); // index pointer instead of shift()

  // When the server sends a new position (e.g. after reconnect), snap to it
  const lastServerPos = useRef(props.position);
  useEffect(() => {
    if (
      group.current &&
      props.position &&
      (props.position.x !== lastServerPos.current?.x ||
        props.position.z !== lastServerPos.current?.z)
    ) {
      group.current.position.copy(props.position);
      // Clear any stale path so the avatar doesn't walk from old position
      pathRef.current = [];
      pathIndexRef.current = 0;
    }
    lastServerPos.current = props.position;
  }, [props.position]);
  const { gridToVector3 } = useGrid();

  const group = useRef();
  const { scene } = useGLTF(avatarUrl);
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);

  const { animations: walkAnimation } = useGLTF("/animations/M_Walk_001.glb");
  const { animations: danceAnimation } = useGLTF(
    "/animations/M_Dances_001.glb"
  );
  const { animations: idleAnimation } = useGLTF(
    "/animations/M_Standing_Idle_001.glb"
  );

  const { actions } = useAnimations(
    [walkAnimation[0], idleAnimation[0], danceAnimation[0]],
    avatar
  );

  // Use refs for animation state to avoid re-renders from useFrame
  const animationRef = useRef("M_Standing_Idle_001");
  const isDancingRef = useRef(false);
  const initRef = useRef(false);
  const [showChatBubble, setShowChatBubble] = useState(false);

  // Apply animation changes via ref — only triggers React state when animation actually changes
  const applyAnimation = useCallback((newAnim) => {
    if (animationRef.current === newAnim) return;
    const oldAnim = animationRef.current;
    animationRef.current = newAnim;
    if (actions[oldAnim]) actions[oldAnim].fadeOut(0.32);
    if (actions[newAnim]) {
      actions[newAnim].reset().fadeIn(initRef.current ? 0.32 : 0).play();
      initRef.current = true;
    }
  }, [actions]);

  useEffect(() => {
    clone.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });
  }, [clone]);

  // Initial animation play
  useEffect(() => {
    const anim = animationRef.current;
    if (actions[anim]) {
      actions[anim].reset().fadeIn(0).play();
      initRef.current = true;
    }
  }, [actions, avatarUrl]);

  useEffect(() => {
    function onPlayerDance(value) {
      if (value.id === id) {
        isDancingRef.current = true;
      }
    }
    function onPlayerMove(value) {
      if (value.id === id) {
        const newPath = [];
        value.path?.forEach((gridPosition) => {
          newPath.push(gridToVector3(gridPosition));
        });
        pathRef.current = newPath;
        pathIndexRef.current = 0;
      }
    }

    let chatMessageBubbleTimeout;
    function onPlayerChatMessage(value) {
      if (value.id === id) {
        setChatMessage(value.message);
        clearTimeout(chatMessageBubbleTimeout);
        setShowChatBubble(true);
        chatMessageBubbleTimeout = setTimeout(() => {
          setShowChatBubble(false);
        }, 5000);
      }
    }

    function onPlayerAction(value) {
      if (value.id === id) {
        if (value.action === null) {
          setActionStatus(null);
        } else {
          setActionStatus({ action: value.action, detail: value.detail });
        }
      }
    }

    socket.on("playerMove", onPlayerMove);
    socket.on("playerDance", onPlayerDance);
    socket.on("playerChatMessage", onPlayerChatMessage);
    socket.on("playerAction", onPlayerAction);
    return () => {
      socket.off("playerDance", onPlayerDance);
      socket.off("playerMove", onPlayerMove);
      socket.off("playerChatMessage", onPlayerChatMessage);
      socket.off("playerAction", onPlayerAction);
    };
  }, [id]);

  const [user] = useAtom(userAtom);

  // Throttle visibility checks — only run every N frames
  const frameCountRef = useRef(0);

  useFrame(({ scene: threeScene }, delta) => {
    if (!avatar.current || !group.current) return;

    const hips = avatar.current.getObjectByName("Hips");
    if (hips) hips.position.set(0, hips.position.y, 0);

    const path = pathRef.current;
    const idx = pathIndexRef.current;
    if (idx < path.length && group.current.position.distanceTo(path[idx]) > 0.1) {
      // Reuse _direction vector to avoid allocation per frame
      _direction.copy(group.current.position).sub(path[idx]).normalize().multiplyScalar(MOVEMENT_SPEED * delta);
      group.current.position.sub(_direction);
      group.current.lookAt(path[idx]);
      applyAnimation("M_Walk_001");
      isDancingRef.current = false;
    } else if (idx < path.length) {
      // Advance index pointer instead of array.shift()
      pathIndexRef.current++;
    } else {
      if (isDancingRef.current) {
        applyAnimation("M_Dances_001");
      } else {
        applyAnimation("M_Standing_Idle_001");
      }
    }

    // Distance-based culling — check every 15 frames to reduce overhead
    frameCountRef.current++;
    if (frameCountRef.current % 15 === 0) {
      const character = threeScene.getObjectByName(`character-${user}`);
      if (character && group.current) {
        const dx = character.position.x - group.current.position.x;
        const dz = character.position.z - group.current.position.z;
        const distSq = dx * dx + dz * dz;
        const newNearby = distSq < RENDER_DISTANCE_SQ;
        const newShowHtml = distSq < HTML_DISTANCE_SQ;
        // Only trigger re-render when visibility actually changes
        if (newNearby !== isNearbyRef.current || newShowHtml !== showHtmlRef.current) {
          isNearbyRef.current = newNearby;
          showHtmlRef.current = newShowHtml;
          forceUpdate((n) => n + 1);
        }
      } else if (!character && !isNearbyRef.current) {
        // User's own character not in scene yet (e.g. loading after reconnect)
        // Default to visible so avatars aren't stuck hidden
        isNearbyRef.current = true;
        showHtmlRef.current = true;
        forceUpdate((n) => n + 1);
      }
    }
  });

  return (
    <group
      ref={group}
      {...props}
      position={position}
      dispose={null}
      name={`character-${id}`}
      visible={isNearbyRef.current || id === user}
    >
      {(showHtmlRef.current || id === user) && (
        <Html position-y={2} center distanceFactor={8} style={{ overflow: 'visible' }}>
          <div className="w-60 max-w-full pointer-events-none overflow-visible">
            {/* Action status indicator — hidden for bots to reduce visual noise */}
            {actionStatus && !showChatBubble && !isBot && (
              <div
                className={`text-center mb-1 p-1.5 px-3 rounded-lg border transition-opacity duration-300 ${
                  actionStatus.action === "thinking"
                    ? "bg-yellow-100/60 border-yellow-300/40 backdrop-blur-sm"
                    : actionStatus.action === "building"
                    ? "bg-orange-100/60 border-orange-300/40 backdrop-blur-sm"
                    : actionStatus.action === "done"
                    ? "bg-green-100/60 border-green-300/40 backdrop-blur-sm"
                    : "bg-blue-100/60 border-blue-300/40 backdrop-blur-sm"
                }`}
              >
                <p className="text-xs text-gray-700 leading-snug whitespace-nowrap">
                  {actionStatus.action === "thinking" && "🤔 "}
                  {actionStatus.action === "building" && "🔨 "}
                  {actionStatus.action === "done" && "✅ "}
                  {actionStatus.action === "walking" && "🚶 "}
                  {actionStatus.action === "chatting" && "💬 "}
                  {actionStatus.action === "dancing" && "💃 "}
                  {actionStatus.action === "emoting" && "😊 "}
                  {actionStatus.detail}
                </p>
              </div>
            )}
            {/* Chat bubble */}
            <div
              className={`text-center break-words p-2 px-4 rounded-xl bg-white/40 backdrop-blur-sm border border-white/20 transition-opacity duration-500 ${
                showChatBubble ? "opacity-100" : "opacity-0"
              }`}
            >
              <p className="text-[10px] font-bold text-gray-600 mb-0.5 truncate">
                {name} {isBot && <span className="text-blue-400 font-semibold">[BOT]</span>}
              </p>
              <p className="text-sm text-black leading-snug">{chatMessage}</p>
            </div>
          </div>
        </Html>
      )}
      <motion.group
        initial={{
          y: 3,
          rotateY: Math.PI * 4,
          scale: 0,
        }}
        animate={{
          y: 0,
          rotateY: 0,
          scale: 1,
        }}
        transition={{
          delay: 0.8,
          mass: 5,
          stiffness: 200,
          damping: 42,
        }}
      >
        <primitive object={clone} ref={avatar} />
      </motion.group>
    </group>
  );
});

// Preload is handled dynamically per-avatar, no static preload needed
useGLTF.preload("/animations/M_Walk_001.glb");
useGLTF.preload("/animations/M_Standing_Idle_001.glb");
useGLTF.preload("/animations/M_Dances_001.glb");
useGLTF.preload("/animations/M_Standing_Expressions_001.glb");
