/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { atom, useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState, memo, useCallback } from "react";
import { SkeletonUtils } from "three-stdlib";
import { useGrid } from "../hooks/useGrid";
import { socket, userAtom } from "./SocketManager";

import * as THREE from "three";
import { motion } from "framer-motion-3d";

// Atom to track which character's profile popup is open
export const selectedCharacterAtom = atom(null);
export const followedCharacterAtom = atom(null);

const MOVEMENT_SPEED = 4;
// How fast the character rotates to face movement direction (radians/sec)
const ROTATION_SPEED = 12;
// Arrival threshold — snap to waypoint when this close
const ARRIVAL_THRESHOLD = 0.1;

// Distance threshold (squared) for rendering avatars — avatars beyond this are culled
const RENDER_DISTANCE_SQ = 30 * 30;
// Closer distance for showing HTML overlays (chat bubbles, action indicators)
const HTML_DISTANCE_SQ = 18 * 18;

// Reusable vectors to avoid allocations in the hot loop
const _direction = new THREE.Vector3();
const _targetQuat = new THREE.Quaternion();
const _lookMatrix = new THREE.Matrix4();
const _up = new THREE.Vector3(0, 1, 0);

export const Avatar = memo(function Avatar({
  id,
  avatarUrl = "https://models.readyplayer.me/64f0265b1db75f90dcfd9e2c.glb",
  name = "Player",
  isBot = false,
  gridPosition,
}) {
  const [chatMessage, setChatMessage] = useState("");
  const [actionStatus, setActionStatus] = useState(null); // { action, detail }
  const [, setSelectedCharacter] = useAtom(selectedCharacterAtom);
  const [followedCharacter, setFollowedCharacter] = useAtom(followedCharacterAtom);
  const { gridToVector3 } = useGrid();
  const position = useMemo(() => gridToVector3(gridPosition), []);
  // Use refs for culling state to avoid re-renders from useFrame distance checks
  const isNearbyRef = useRef(true);
  const showHtmlRef = useRef(true);
  const [, forceUpdate] = useState(0);

  const avatar = useRef();
  const pathRef = useRef([]);
  const pathIndexRef = useRef(0); // index pointer instead of shift()

  // When the server sends a new position (e.g. after reconnect), snap to it
  const lastServerGridPos = useRef(gridPosition);
  useEffect(() => {
    if (
      group.current &&
      gridPosition &&
      (gridPosition[0] !== lastServerGridPos.current?.[0] ||
        gridPosition[1] !== lastServerGridPos.current?.[1])
    ) {
      const newPos = gridToVector3(gridPosition);
      group.current.position.copy(newPos);
      // Clear any stale path so the avatar doesn't walk from old position
      pathRef.current = [];
      pathIndexRef.current = 0;
    }
    lastServerGridPos.current = gridPosition;
  }, [gridPosition]);

  const group = useRef();
  const { scene } = useGLTF(avatarUrl);
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);

  const { animations: walkAnimation } = useGLTF("/animations/M_Walk_001.glb");
  const { animations: danceAnimation } = useGLTF(
    "/animations/M_Dances_001.glb"
  );
  const { animations: idleAnimation } = useGLTF(
    "/animations/M_Standing_Idle_001.glb"
  );
  const { animations: waveAnimation } = useGLTF(
    "/animations/M_Standing_Expressions_001.glb"
  );

  const { actions } = useAnimations(
    [walkAnimation[0], idleAnimation[0], danceAnimation[0], waveAnimation[0]],
    avatar
  );

  // Use refs for animation state to avoid re-renders from useFrame
  const animationRef = useRef("M_Standing_Idle_001");
  const isDancingRef = useRef(false);
  const isWavingRef = useRef(false);
  const waveTargetIdRef = useRef(null);
  const waveTimeoutRef = useRef(null);
  const initRef = useRef(false);
  // Random offset so characters don't animate in lockstep
  const animOffsetRef = useRef(Math.random());
  const [showChatBubble, setShowChatBubble] = useState(false);

  // Apply animation changes via ref — only triggers React state when animation actually changes
  const applyAnimation = useCallback((newAnim) => {
    if (animationRef.current === newAnim) return;
    const oldAnim = animationRef.current;
    animationRef.current = newAnim;
    if (actions[oldAnim]) actions[oldAnim].fadeOut(0.32);
    if (actions[newAnim]) {
      const action = actions[newAnim];
      action.reset().fadeIn(initRef.current ? 0.32 : 0).play();
      // Offset the starting time so characters aren't in sync
      const clip = action.getClip();
      if (clip) action.time = animOffsetRef.current * clip.duration;
      initRef.current = true;
    }
  }, [actions]);

  useEffect(() => {
    clone.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });
  }, [clone]);

  // Initial animation play
  useEffect(() => {
    const anim = animationRef.current;
    if (actions[anim]) {
      const action = actions[anim];
      action.reset().fadeIn(0).play();
      // Offset so each character starts at a different point in the cycle
      const clip = action.getClip();
      if (clip) action.time = animOffsetRef.current * clip.duration;
      initRef.current = true;
    }
  }, [actions, avatarUrl]);

  useEffect(() => {
    function onPlayerDance(value) {
      if (value.id === id) {
        isDancingRef.current = true;
      }
    }
    function onPlayerMove(value) {
      if (value.id === id) {
        const newPath = [];
        value.path?.forEach((gridPosition) => {
          newPath.push(gridToVector3(gridPosition));
        });
        pathRef.current = newPath;
        pathIndexRef.current = 0;
        // Update lastServerGridPos to the path endpoint so that subsequent
        // characters/mapUpdate broadcasts (which carry the endpoint position)
        // don't trigger a snap-back while the character is walking.
        if (value.path && value.path.length > 0) {
          lastServerGridPos.current = value.path[value.path.length - 1];
        }
      }
    }

    let chatMessageBubbleTimeout;
    function onPlayerChatMessage(value) {
      if (value.id === id) {
        setChatMessage(value.message);
        clearTimeout(chatMessageBubbleTimeout);
        setShowChatBubble(true);
        chatMessageBubbleTimeout = setTimeout(() => {
          setShowChatBubble(false);
        }, 5000);
      }
    }

    function onPlayerAction(value) {
      if (value.id === id) {
        if (value.action === null) {
          setActionStatus(null);
        } else {
          setActionStatus({ action: value.action, detail: value.detail });
        }
      }
    }

    function onPlayerWaveAt(value) {
      if (value.id === id) {
        waveTargetIdRef.current = value.targetId;
        isWavingRef.current = true;
        isDancingRef.current = false;
        // Stop moving so the character stands and waves
        pathRef.current = [];
        pathIndexRef.current = 0;
        // Auto-stop waving after 3 seconds
        clearTimeout(waveTimeoutRef.current);
        waveTimeoutRef.current = setTimeout(() => {
          isWavingRef.current = false;
          waveTargetIdRef.current = null;
        }, 3000);
      }
    }

    socket.on("playerMove", onPlayerMove);
    socket.on("playerDance", onPlayerDance);
    socket.on("playerChatMessage", onPlayerChatMessage);
    socket.on("playerAction", onPlayerAction);
    socket.on("playerWaveAt", onPlayerWaveAt);
    return () => {
      socket.off("playerDance", onPlayerDance);
      socket.off("playerMove", onPlayerMove);
      socket.off("playerChatMessage", onPlayerChatMessage);
      socket.off("playerAction", onPlayerAction);
      socket.off("playerWaveAt", onPlayerWaveAt);
      clearTimeout(waveTimeoutRef.current);
    };
  }, [id]);

  const [user] = useAtom(userAtom);

  // Throttle visibility checks — only run every N frames
  const frameCountRef = useRef(0);

  useFrame(({ scene: threeScene }, delta) => {
    if (!avatar.current || !group.current) return;

    const hips = avatar.current.getObjectByName("Hips");
    if (hips) hips.position.set(0, hips.position.y, 0);

    const path = pathRef.current;
    const idx = pathIndexRef.current;
    if (idx < path.length) {
      const target = path[idx];
      const dist = group.current.position.distanceTo(target);

      if (dist > ARRIVAL_THRESHOLD) {
        // --- Smooth rotation via quaternion slerp ---
        _direction.copy(target).sub(group.current.position).normalize();
        _lookMatrix.lookAt(_direction, new THREE.Vector3(), _up);
        _targetQuat.setFromRotationMatrix(_lookMatrix);
        group.current.quaternion.slerp(_targetQuat, Math.min(1, ROTATION_SPEED * delta));

        // --- Movement with deceleration near final waypoint ---
        const isLastWaypoint = idx === path.length - 1;
        // Slow down when approaching the last waypoint for a gentle stop
        const speedScale = isLastWaypoint ? Math.max(0.3, Math.min(1, dist / 1.0)) : 1;
        const step = MOVEMENT_SPEED * speedScale * delta;
        // Don't overshoot the waypoint
        const moveDistance = Math.min(step, dist);

        _direction.copy(target).sub(group.current.position).normalize().multiplyScalar(moveDistance);
        group.current.position.add(_direction);

        applyAnimation("M_Walk_001");
        isDancingRef.current = false;
        isWavingRef.current = false;
      } else {
        // Snap to waypoint and advance
        group.current.position.copy(target);
        pathIndexRef.current++;
      }
    } else if (isWavingRef.current) {
      // Face the target character while waving
      if (waveTargetIdRef.current) {
        const targetObj = threeScene.getObjectByName(`character-${waveTargetIdRef.current}`);
        if (targetObj && group.current) {
          _direction.copy(targetObj.position).sub(group.current.position);
          _direction.y = 0;
          if (_direction.lengthSq() > 0.001) {
            _direction.normalize();
            _lookMatrix.lookAt(_direction, new THREE.Vector3(), _up);
            _targetQuat.setFromRotationMatrix(_lookMatrix);
            group.current.quaternion.slerp(_targetQuat, Math.min(1, ROTATION_SPEED * delta));
          }
        }
      }
      applyAnimation("M_Standing_Expressions_001");
    } else {
      if (isDancingRef.current) {
        applyAnimation("M_Dances_001");
      } else {
        applyAnimation("M_Standing_Idle_001");
      }
    }

    // Distance-based culling — check every 15 frames to reduce overhead
    frameCountRef.current++;
    if (frameCountRef.current % 15 === 0) {
      const character = threeScene.getObjectByName(`character-${user}`);
      if (character && group.current) {
        const dx = character.position.x - group.current.position.x;
        const dz = character.position.z - group.current.position.z;
        const distSq = dx * dx + dz * dz;
        const newNearby = distSq < RENDER_DISTANCE_SQ;
        const newShowHtml = distSq < HTML_DISTANCE_SQ;
        // Only trigger re-render when visibility actually changes
        if (newNearby !== isNearbyRef.current || newShowHtml !== showHtmlRef.current) {
          isNearbyRef.current = newNearby;
          showHtmlRef.current = newShowHtml;
          forceUpdate((n) => n + 1);
        }
      } else if (!character && !isNearbyRef.current) {
        // User's own character not in scene yet (e.g. loading after reconnect)
        // Default to visible so avatars aren't stuck hidden
        isNearbyRef.current = true;
        showHtmlRef.current = true;
        forceUpdate((n) => n + 1);
      }
    }
  });

  const handleCharacterClick = useCallback((e) => {
    e.stopPropagation();
    setSelectedCharacter({ id, name, avatarUrl, isBot, position: group.current?.position });
  }, [id, name, avatarUrl, isBot, setSelectedCharacter]);

  return (
    <group
      ref={group}
      position={position}
      dispose={null}
      name={`character-${id}`}
      visible={isNearbyRef.current || id === user}
      onClick={handleCharacterClick}
      onPointerOver={() => { document.body.style.cursor = "pointer"; }}
      onPointerOut={() => { document.body.style.cursor = "auto"; }}
    >
      {(showHtmlRef.current || id === user) && (
        <>
          {/* Always-visible name label — clickable to open character menu */}
          <Html position-y={2.3} center distanceFactor={8} zIndexRange={[1, 0]} style={{ overflow: 'visible' }}>
            <div
              className="select-none cursor-pointer"
              onClick={(e) => {
                e.stopPropagation();
                setSelectedCharacter({ id, name, avatarUrl, isBot, position: group.current?.position });
              }}
            >
              <div className="flex flex-col items-center justify-center gap-0.5 whitespace-nowrap">
                {isBot && (
                  <span className="text-lg leading-none" style={{ filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.5))" }}>
                    🦀
                  </span>
                )}
                <span
                  className="text-[11px] font-bold px-2 py-0.5 rounded-full"
                  style={{
                    color: isBot ? "#93c5fd" : "#ffffff",
                    background: "rgba(0,0,0,0.45)",
                    backdropFilter: "blur(4px)",
                    textShadow: "0 1px 2px rgba(0,0,0,0.5)",
                  }}
                >
                  {name}
                </span>
              </div>
            </div>
          </Html>
          {/* Chat bubble + action status */}
          <Html position-y={2} center distanceFactor={8} zIndexRange={[1, 0]} style={{ overflow: 'visible' }}>
            <div className="w-60 max-w-full pointer-events-none overflow-visible">
              {/* Action status indicator — hidden for bots to reduce visual noise */}
              {actionStatus && !showChatBubble && !isBot && (
                <div
                  className={`text-center mb-1 p-1.5 px-3 rounded-lg border transition-opacity duration-300 ${
                    actionStatus.action === "thinking"
                      ? "bg-yellow-100/60 border-yellow-300/40 backdrop-blur-sm"
                      : actionStatus.action === "building"
                      ? "bg-orange-100/60 border-orange-300/40 backdrop-blur-sm"
                      : actionStatus.action === "done"
                      ? "bg-green-100/60 border-green-300/40 backdrop-blur-sm"
                      : "bg-blue-100/60 border-blue-300/40 backdrop-blur-sm"
                  }`}
                >
                  <p className="text-xs text-gray-700 leading-snug whitespace-nowrap">
                    {actionStatus.action === "thinking" && "🤔 "}
                    {actionStatus.action === "building" && "🔨 "}
                    {actionStatus.action === "done" && "✅ "}
                    {actionStatus.action === "walking" && "🚶 "}
                    {actionStatus.action === "chatting" && "💬 "}
                    {actionStatus.action === "dancing" && "💃 "}
                    {actionStatus.action === "emoting" && "😊 "}
                    {actionStatus.detail}
                  </p>
                </div>
              )}
              {/* Chat bubble */}
              <div
                className={`text-center break-words p-2 px-4 rounded-xl bg-white/40 backdrop-blur-sm border border-white/20 transition-opacity duration-500 ${
                  showChatBubble ? "opacity-100" : "opacity-0"
                }`}
              >
                <p className="text-[10px] font-bold text-gray-600 mb-0.5 truncate">
                  {name} {isBot && <span className="text-blue-400 font-semibold">[BOT]</span>}
                </p>
                <p className="text-sm text-black leading-snug">{chatMessage}</p>
              </div>
            </div>
          </Html>
        </>
      )}
      {/* Invisible click hitbox — skinned meshes don't raycast reliably */}
      <mesh position-y={0.9}>
        <capsuleGeometry args={[0.3, 1.0, 4, 8]} />
        <meshBasicMaterial transparent opacity={0} depthWrite={false} />
      </mesh>
      <motion.group
        initial={{
          y: 3,
          rotateY: Math.PI * 4,
          scale: 0,
        }}
        animate={{
          y: 0,
          rotateY: 0,
          scale: 1,
        }}
        transition={{
          delay: 0.8,
          mass: 5,
          stiffness: 200,
          damping: 42,
        }}
      >
        <primitive object={clone} ref={avatar} />
      </motion.group>
    </group>
  );
});

export const CharacterMenu = () => {
  const [selectedCharacter, setSelectedCharacter] = useAtom(selectedCharacterAtom);
  const [followedCharacter, setFollowedCharacter] = useAtom(followedCharacterAtom);
  const [user] = useAtom(userAtom);
  const [imgError, setImgError] = useState(false);
  const prevCharIdRef = useRef(null);
  if (selectedCharacter?.id !== prevCharIdRef.current) {
    prevCharIdRef.current = selectedCharacter?.id;
    if (imgError) setImgError(false);
  }

  if (!selectedCharacter || selectedCharacter.id === user) return null;

  const isFollowing = followedCharacter?.id === selectedCharacter.id;
  const thumbnailUrl = selectedCharacter.avatarUrl
    ? selectedCharacter.avatarUrl.split("?")[0].replace(".glb", ".png") + "?size=256"
    : "";

  const handleWave = () => {
    socket.emit("wave:at", selectedCharacter.id);
    setSelectedCharacter(null);
  };

  const handleFollow = () => {
    if (isFollowing) {
      setFollowedCharacter(null);
    } else {
      setFollowedCharacter({ id: selectedCharacter.id, name: selectedCharacter.name });
    }
    setSelectedCharacter(null);
  };

  const handleClose = () => {
    setSelectedCharacter(null);
  };

  return (
    <div className="fixed inset-0 z-[20] flex items-center justify-center">
      {/* Backdrop — click to close */}
      <div className="absolute inset-0 bg-black/30" onClick={handleClose} />

      <div className="relative pointer-events-auto bg-gray-900/90 backdrop-blur-md rounded-2xl border border-white/10 shadow-2xl min-w-[240px] max-w-[280px] overflow-hidden">
        {/* Avatar thumbnail */}
        <div className="bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center py-5">
          <div className="w-20 h-20 rounded-full overflow-hidden bg-gray-700 border-2 border-white/20 shadow-lg">
            {!imgError ? (
              <img
                src={thumbnailUrl}
                alt={selectedCharacter.name}
                className="w-full h-full object-cover"
                onError={() => setImgError(true)}
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-gray-500">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                </svg>
              </div>
            )}
          </div>
        </div>

        {/* Name + badge */}
        <div className="text-center px-4 pt-3 pb-2">
          <p className="text-white font-semibold text-base">{selectedCharacter.name || "Player"}</p>
          <span className={`inline-block mt-1 text-xs font-semibold px-2.5 py-0.5 rounded-full ${
            selectedCharacter.isBot
              ? "bg-blue-500/20 text-blue-300"
              : "bg-green-500/20 text-green-300"
          }`}>
            {selectedCharacter.isBot ? "Bot" : "Player"}
          </span>
        </div>

        {/* Actions */}
        <div className="flex flex-col gap-2 p-3 pt-2">
          <button
            onClick={handleWave}
            className="w-full flex items-center gap-2 px-3 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-white text-sm transition-colors text-left"
          >
            <span className="text-base">{"\u{1F44B}"}</span>
            <span>Wave at {selectedCharacter.name || "them"}</span>
          </button>
          <button
            onClick={handleFollow}
            className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm transition-colors text-left ${
              isFollowing
                ? "bg-blue-500/20 hover:bg-blue-500/30 text-blue-300"
                : "bg-white/5 hover:bg-white/10 text-white"
            }`}
          >
            <span className="text-base">{isFollowing ? "\u{1F441}\uFE0F" : "\u{1F4F7}"}</span>
            <span>{isFollowing ? "Unfollow camera" : `Follow ${selectedCharacter.name || "them"}`}</span>
          </button>
        </div>

        {/* Close button */}
        <button
          onClick={handleClose}
          className="absolute top-2 right-2 text-gray-400 hover:text-white transition-colors w-7 h-7 flex items-center justify-center rounded-full bg-black/30 hover:bg-black/50"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  );
};

// Preload is handled dynamically per-avatar, no static preload needed
useGLTF.preload("/animations/M_Walk_001.glb");
useGLTF.preload("/animations/M_Standing_Idle_001.glb");
useGLTF.preload("/animations/M_Dances_001.glb");
useGLTF.preload("/animations/M_Standing_Expressions_001.glb");
