/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { atom, useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState, memo, useCallback } from "react";
import { SkeletonUtils } from "three-stdlib";
import { useGrid } from "../hooks/useGrid";
import { socket, userAtom, avatarDispatch } from "./SocketManager";
import { dmPanelTargetAtom } from "./DirectMessagePanel";

import * as THREE from "three";
import { motion } from "framer-motion-3d";

// Atom to track which character's profile popup is open
export const selectedCharacterAtom = atom(null);
export const followedCharacterAtom = atom(null);

const MOVEMENT_SPEED = 4;
// How fast the character rotates to face movement direction (radians/sec)
const ROTATION_SPEED = 12;
// Arrival threshold — snap to waypoint when this close
const ARRIVAL_THRESHOLD = 0.1;

// Distance threshold (squared) for rendering avatars — avatars beyond this are culled
const RENDER_DISTANCE_SQ = 30 * 30;
// Hysteresis: use a slightly larger radius before re-culling to prevent flicker
const RENDER_DISTANCE_HIDE_SQ = 33 * 33;

// Distance tier thresholds with hysteresis to prevent animation throttle flicker
const NEAR_ENTER_SQ = 15 * 15;
const NEAR_EXIT_SQ = 17 * 17;
const MID_ENTER_SQ = RENDER_DISTANCE_SQ;
const MID_EXIT_SQ = RENDER_DISTANCE_HIDE_SQ;

// Reusable vectors to avoid allocations in the hot loop
const _direction = new THREE.Vector3();
const _targetQuat = new THREE.Quaternion();
const _lookMatrix = new THREE.Matrix4();
const _up = new THREE.Vector3(0, 1, 0);
const _zero = new THREE.Vector3();

export const Avatar = memo(function Avatar({
  id,
  avatarUrl = "https://models.readyplayer.me/64f0265b1db75f90dcfd9e2c.glb",
  name = "Player",
  isBot = false,
  gridPosition,
  showHtmlOverlay = true,
}) {
  const [chatMessage, setChatMessage] = useState("");
  const [actionStatus, setActionStatus] = useState(null); // { action, detail }
  const [, setSelectedCharacter] = useAtom(selectedCharacterAtom);
  const [followedCharacter, setFollowedCharacter] = useAtom(followedCharacterAtom);
  const { gridToVector3 } = useGrid();
  const position = useMemo(() => gridToVector3(gridPosition), []);
  // Use refs for culling state to avoid re-renders from useFrame distance checks
  const isNearbyRef = useRef(true);
  const distanceTierRef = useRef("near"); // "near" (<15u), "mid" (15-30u), "far" (>30u)
  const midAnimAccRef = useRef(0);

  const avatar = useRef();
  const hipsRef = useRef(null);
  const pathRef = useRef([]);
  const pathIndexRef = useRef(0); // index pointer instead of shift()

  // When the server sends a new position (e.g. after reconnect), snap to it
  const lastServerGridPos = useRef(gridPosition);
  useEffect(() => {
    if (
      group.current &&
      gridPosition &&
      (gridPosition[0] !== lastServerGridPos.current?.[0] ||
        gridPosition[1] !== lastServerGridPos.current?.[1])
    ) {
      const newPos = gridToVector3(gridPosition);
      group.current.position.copy(newPos);
      // Clear any stale path so the avatar doesn't walk from old position
      pathRef.current = [];
      pathIndexRef.current = 0;
    }
    lastServerGridPos.current = gridPosition;
  }, [gridPosition]);

  const group = useRef();
  const { scene } = useGLTF(avatarUrl);
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // Task 7: Share GPU geometry buffers — only 4 unique avatar URLs exist
  useMemo(() => {
    const origMeshes = [];
    scene.traverse((child) => {
      if (child.isMesh) origMeshes.push(child);
    });
    let i = 0;
    clone.traverse((child) => {
      if (child.isMesh && i < origMeshes.length) {
        child.geometry = origMeshes[i].geometry; // share GPU buffer
        i++;
      }
    });
  }, [clone, scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);

  const { animations: walkAnimation } = useGLTF("/animations/M_Walk_001.glb");
  const { animations: danceAnimation } = useGLTF(
    "/animations/M_Dances_001.glb"
  );
  const { animations: idleAnimation } = useGLTF(
    "/animations/M_Standing_Idle_001.glb"
  );
  const { animations: waveAnimation } = useGLTF(
    "/animations/M_Standing_Expressions_001.glb"
  );

  const { actions, mixer } = useAnimations(
    [walkAnimation[0], idleAnimation[0], danceAnimation[0], waveAnimation[0]],
    avatar
  );

  // Use refs for animation state to avoid re-renders from useFrame
  const animationRef = useRef("M_Standing_Idle_001");
  const isDancingRef = useRef(false);
  const isWavingRef = useRef(false);
  const waveTargetIdRef = useRef(null);
  const waveTimeoutRef = useRef(null);
  const initRef = useRef(false);
  // Random offset so characters don't animate in lockstep
  const animOffsetRef = useRef(Math.random());
  const [showChatBubble, setShowChatBubble] = useState(false);

  // Apply animation changes via ref — only triggers React state when animation actually changes
  const applyAnimation = useCallback((newAnim) => {
    if (animationRef.current === newAnim) return;
    const oldAnim = animationRef.current;
    animationRef.current = newAnim;
    if (actions[oldAnim]) actions[oldAnim].fadeOut(0.32);
    if (actions[newAnim]) {
      const action = actions[newAnim];
      action.reset().fadeIn(initRef.current ? 0.32 : 0).play();
      // Offset the starting time so characters aren't in sync
      const clip = action.getClip();
      if (clip) action.time = animOffsetRef.current * clip.duration;
      initRef.current = true;
    }
  }, [actions]);

  useEffect(() => {
    clone.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = false;
        child.receiveShadow = true;
      }
    });
  }, [clone]);

  // Initial animation play
  useEffect(() => {
    const anim = animationRef.current;
    if (actions[anim]) {
      const action = actions[anim];
      action.reset().fadeIn(0).play();
      // Offset so each character starts at a different point in the cycle
      const clip = action.getClip();
      if (clip) action.time = animOffsetRef.current * clip.duration;
      initRef.current = true;
    }
  }, [actions, avatarUrl]);

  useEffect(() => {
    function onPlayerDance(value) {
      isDancingRef.current = true;
    }
    function onPlayerMove(value) {
      const newPath = [];
      value.path?.forEach((gridPosition) => {
        newPath.push(gridToVector3(gridPosition));
      });
      // If avatar is currently culled, skip path animation entirely —
      // just update server position so it snaps correctly when it becomes visible
      if (!isNearbyRef.current && id !== user) {
        pathRef.current = [];
        pathIndexRef.current = 0;
        if (value.path && value.path.length > 0) {
          lastServerGridPos.current = value.path[value.path.length - 1];
        }
        return;
      }
      pathRef.current = newPath;
      pathIndexRef.current = 0;
      if (value.path && value.path.length > 0) {
        lastServerGridPos.current = value.path[value.path.length - 1];
      }
    }

    let chatMessageBubbleTimeout;
    function onPlayerChatMessage(value) {
      setChatMessage(value.message);
      clearTimeout(chatMessageBubbleTimeout);
      setShowChatBubble(true);
      chatMessageBubbleTimeout = setTimeout(() => {
        setShowChatBubble(false);
      }, 5000);
    }

    function onPlayerAction(value) {
      if (value.action === null) {
        setActionStatus(null);
      } else {
        setActionStatus({ action: value.action, detail: value.detail });
      }
    }

    function onPlayerWaveAt(value) {
      waveTargetIdRef.current = value.targetId;
      isWavingRef.current = true;
      isDancingRef.current = false;
      pathRef.current = [];
      pathIndexRef.current = 0;
      clearTimeout(waveTimeoutRef.current);
      waveTimeoutRef.current = setTimeout(() => {
        isWavingRef.current = false;
        waveTargetIdRef.current = null;
      }, 3000);
    }

    // Register on dispatch maps — O(1) lookup, no per-avatar socket listener
    avatarDispatch.playerMove.set(id, onPlayerMove);
    avatarDispatch.playerDance.set(id, onPlayerDance);
    avatarDispatch.playerChatMessage.set(id, onPlayerChatMessage);
    avatarDispatch.playerAction.set(id, onPlayerAction);
    avatarDispatch.playerWaveAt.set(id, onPlayerWaveAt);

    return () => {
      avatarDispatch.playerMove.delete(id);
      avatarDispatch.playerDance.delete(id);
      avatarDispatch.playerChatMessage.delete(id);
      avatarDispatch.playerAction.delete(id);
      avatarDispatch.playerWaveAt.delete(id);
      clearTimeout(chatMessageBubbleTimeout);
      clearTimeout(waveTimeoutRef.current);
    };
  }, [id]);

  const [user] = useAtom(userAtom);

  // Throttle visibility checks — only run every N frames
  const frameCountRef = useRef(0);

  useFrame(({ scene: threeScene }, delta) => {
    if (!avatar.current || !group.current) return;

    // Distance-based culling — check every 15 frames
    frameCountRef.current++;
    if (frameCountRef.current % 15 === 0) {
      const character = threeScene.getObjectByName(`character-${user}`);
      if (character && group.current) {
        const dx = character.position.x - group.current.position.x;
        const dz = character.position.z - group.current.position.z;
        const distSq = dx * dx + dz * dz;
        // Hysteresis: use tighter threshold to show, wider to hide
        const newNearby = isNearbyRef.current
          ? distSq < RENDER_DISTANCE_HIDE_SQ
          : distSq < RENDER_DISTANCE_SQ;
        if (newNearby !== isNearbyRef.current) {
          isNearbyRef.current = newNearby;
          group.current.visible = newNearby || id === user;
          // When becoming visible after being culled, snap to last known server position
          // to prevent stale position artifacts
          if (newNearby && lastServerGridPos.current) {
            const snapPos = gridToVector3(lastServerGridPos.current);
            group.current.position.copy(snapPos);
            // Clear any stale path so avatar doesn't walk from wrong position
            pathRef.current = [];
            pathIndexRef.current = 0;
          }
        }
        // Update distance tier with hysteresis to prevent animation throttle flicker
        if (distanceTierRef.current === "near") {
          if (distSq >= NEAR_EXIT_SQ) {
            distanceTierRef.current = distSq < MID_EXIT_SQ ? "mid" : "far";
          }
        } else if (distanceTierRef.current === "mid") {
          if (distSq < NEAR_ENTER_SQ) {
            distanceTierRef.current = "near";
          } else if (distSq >= MID_EXIT_SQ) {
            distanceTierRef.current = "far";
          }
        } else {
          // "far"
          if (distSq < NEAR_ENTER_SQ) {
            distanceTierRef.current = "near";
          } else if (distSq < MID_ENTER_SQ) {
            distanceTierRef.current = "mid";
          }
        }
      } else if (!character && !isNearbyRef.current) {
        isNearbyRef.current = true;
        group.current.visible = true;
        distanceTierRef.current = "near";
      }
    }

    // Skip all movement/animation for non-visible distant avatars
    if (!isNearbyRef.current && id !== user) return;

    if (!hipsRef.current) {
      hipsRef.current = avatar.current.getObjectByName("Hips");
    }
    const hips = hipsRef.current;
    // Only reset hips X/Z drift, preserve Y for vertical bob
    if (hips) {
      // Clamp rather than zero — prevents walk root motion from drifting
      // the character away, but allows small hip sway from animation
      const hx = hips.position.x;
      const hz = hips.position.z;
      if (Math.abs(hx) > 0.05 || Math.abs(hz) > 0.05) {
        hips.position.set(0, hips.position.y, 0);
      }
    }

    const path = pathRef.current;
    const idx = pathIndexRef.current;
    if (idx < path.length) {
      const target = path[idx];
      const dist = group.current.position.distanceTo(target);

      if (dist > ARRIVAL_THRESHOLD) {
        _direction.copy(target).sub(group.current.position).normalize();
        _lookMatrix.lookAt(_direction, _zero, _up);
        _targetQuat.setFromRotationMatrix(_lookMatrix);
        group.current.quaternion.slerp(_targetQuat, Math.min(1, ROTATION_SPEED * delta));

        const isLastWaypoint = idx === path.length - 1;
        const speedScale = isLastWaypoint ? Math.max(0.3, Math.min(1, dist / 1.0)) : 1;
        const step = MOVEMENT_SPEED * speedScale * delta;
        const moveDistance = Math.min(step, dist);

        _direction.copy(target).sub(group.current.position).normalize().multiplyScalar(moveDistance);
        group.current.position.add(_direction);

        applyAnimation("M_Walk_001");
        isDancingRef.current = false;
        isWavingRef.current = false;
      } else {
        group.current.position.copy(target);
        pathIndexRef.current++;
      }
    } else if (isWavingRef.current) {
      if (waveTargetIdRef.current) {
        const targetObj = threeScene.getObjectByName(`character-${waveTargetIdRef.current}`);
        if (targetObj && group.current) {
          _direction.copy(targetObj.position).sub(group.current.position);
          _direction.y = 0;
          if (_direction.lengthSq() > 0.001) {
            _direction.normalize();
            _lookMatrix.lookAt(_direction, _zero, _up);
            _targetQuat.setFromRotationMatrix(_lookMatrix);
            group.current.quaternion.slerp(_targetQuat, Math.min(1, ROTATION_SPEED * delta));
          }
        }
      }
      applyAnimation("M_Standing_Expressions_001");
    } else {
      if (isDancingRef.current) {
        applyAnimation("M_Dances_001");
      } else {
        applyAnimation("M_Standing_Idle_001");
      }
    }

    // Task 4: Throttle animation mixer for "mid" distance tier (4 fps)
    if (distanceTierRef.current === "mid" && mixer) {
      midAnimAccRef.current += delta;
      if (midAnimAccRef.current >= 0.25) {
        mixer.update(midAnimAccRef.current);
        midAnimAccRef.current = 0;
      }
      // Prevent drei's automatic mixer.update by setting timeScale to 0
      if (mixer.timeScale !== 0) mixer.timeScale = 0;
    } else if (mixer) {
      // Near tier: normal speed — flush any accumulated mid-tier time first
      if (mixer.timeScale !== 1) {
        if (midAnimAccRef.current > 0) {
          mixer.update(midAnimAccRef.current);
        }
        mixer.timeScale = 1;
        midAnimAccRef.current = 0;
      }
    }
  });

  const handleCharacterClick = useCallback((e) => {
    e.stopPropagation();
    setSelectedCharacter({ id, name, avatarUrl, isBot, position: group.current?.position });
  }, [id, name, avatarUrl, isBot, setSelectedCharacter]);

  return (
    <group
      ref={group}
      position={position}
      dispose={null}
      name={`character-${id}`}
      visible={true}
      onClick={handleCharacterClick}
      onPointerOver={() => { document.body.style.cursor = "pointer"; }}
      onPointerOut={() => { document.body.style.cursor = "auto"; }}
    >
      {(showHtmlOverlay || id === user) && (
        <>
          {/* Always-visible name label — clickable to open character menu */}
          <Html position-y={2.3} center distanceFactor={8} zIndexRange={[1, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
            <div
              className="select-none cursor-pointer"
              style={{ pointerEvents: 'auto' }}
              onClick={(e) => {
                e.stopPropagation();
                setSelectedCharacter({ id, name, avatarUrl, isBot, position: group.current?.position });
              }}
            >
              <div className="flex flex-col items-center justify-center gap-0.5 whitespace-nowrap">
                {isBot && (
                  <span className="text-lg leading-none" style={{ filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.5))" }}>
                    🦀
                  </span>
                )}
                <span
                  className="text-[11px] font-bold px-2 py-0.5 rounded-full"
                  style={{
                    color: isBot ? "#93c5fd" : "#ffffff",
                    background: "rgba(0,0,0,0.45)",
                    backdropFilter: "blur(4px)",
                    textShadow: "0 1px 2px rgba(0,0,0,0.5)",
                  }}
                >
                  {name}
                </span>
              </div>
            </div>
          </Html>
          {/* Chat bubble + action status */}
          <Html position-y={2} center distanceFactor={8} zIndexRange={[1, 0]} style={{ overflow: 'visible', pointerEvents: 'none' }}>
            <div className="w-60 max-w-full pointer-events-none overflow-visible">
              {/* Action status indicator — hidden for bots to reduce visual noise */}
              {actionStatus && !showChatBubble && !isBot && (
                <div
                  className={`text-center mb-1 p-1.5 px-3 rounded-lg border transition-opacity duration-300 ${
                    actionStatus.action === "thinking"
                      ? "bg-yellow-100/80 border-yellow-300/40"
                      : actionStatus.action === "building"
                      ? "bg-orange-100/80 border-orange-300/40"
                      : actionStatus.action === "done"
                      ? "bg-green-100/80 border-green-300/40"
                      : "bg-blue-100/80 border-blue-300/40"
                  }`}
                >
                  <p className="text-xs text-gray-700 leading-snug whitespace-nowrap">
                    {actionStatus.action === "thinking" && "🤔 "}
                    {actionStatus.action === "building" && "🔨 "}
                    {actionStatus.action === "done" && "✅ "}
                    {actionStatus.action === "walking" && "🚶 "}
                    {actionStatus.action === "chatting" && "💬 "}
                    {actionStatus.action === "dancing" && "💃 "}
                    {actionStatus.action === "emoting" && "😊 "}
                    {actionStatus.detail}
                  </p>
                </div>
              )}
              {/* Chat bubble */}
              <div
                className={`text-center break-words p-2 px-4 rounded-xl bg-white/80 border border-white/20 transition-opacity duration-500 ${
                  showChatBubble ? "opacity-100" : "opacity-0"
                }`}
              >
                <p className="text-[10px] font-bold text-gray-600 mb-0.5 truncate">
                  {name} {isBot && <span className="text-blue-400 font-semibold">[BOT]</span>}
                </p>
                <p className="text-sm text-black leading-snug">{chatMessage}</p>
              </div>
            </div>
          </Html>
        </>
      )}
      {/* Invisible click hitbox — skinned meshes don't raycast reliably */}
      <mesh position-y={0.9}>
        <capsuleGeometry args={[0.3, 1.0, 4, 8]} />
        <meshBasicMaterial transparent opacity={0} depthWrite={false} />
      </mesh>
      <motion.group
        initial={{
          y: 1.5,
          rotateY: Math.PI * 2,
          scale: 0,
        }}
        animate={{
          y: 0,
          rotateY: 0,
          scale: 1,
        }}
        transition={{
          delay: 0.15,
          mass: 2,
          stiffness: 300,
          damping: 30,
        }}
      >
        <primitive object={clone} ref={avatar} />
      </motion.group>
    </group>
  );
});

export const CharacterMenu = () => {
  const [selectedCharacter, setSelectedCharacter] = useAtom(selectedCharacterAtom);
  const [followedCharacter, setFollowedCharacter] = useAtom(followedCharacterAtom);
  const [, setDmPanelTarget] = useAtom(dmPanelTargetAtom);
  const [user] = useAtom(userAtom);
  const [imgError, setImgError] = useState(false);
  const prevCharIdRef = useRef(null);
  if (selectedCharacter?.id !== prevCharIdRef.current) {
    prevCharIdRef.current = selectedCharacter?.id;
    if (imgError) setImgError(false);
  }

  if (!selectedCharacter || selectedCharacter.id === user) return null;

  const isFollowing = followedCharacter?.id === selectedCharacter.id;
  const thumbnailUrl = selectedCharacter.avatarUrl
    ? selectedCharacter.avatarUrl.split("?")[0].replace(".glb", ".png") + "?size=256"
    : "";

  const handleWave = () => {
    socket.emit("wave:at", selectedCharacter.id);
    setSelectedCharacter(null);
  };

  const handleFollow = () => {
    if (isFollowing) {
      setFollowedCharacter(null);
    } else {
      setFollowedCharacter({ id: selectedCharacter.id, name: selectedCharacter.name });
    }
    setSelectedCharacter(null);
  };

  const handleTalkTo = () => {
    setDmPanelTarget({ id: selectedCharacter.id, name: selectedCharacter.name, isBot: selectedCharacter.isBot });
    setSelectedCharacter(null);
  };

  const handleShop = () => {
    setDmPanelTarget({ id: selectedCharacter.id, name: selectedCharacter.name, isBot: selectedCharacter.isBot });
    // Set a brief delay then switch tab via a custom event
    setTimeout(() => window.dispatchEvent(new CustomEvent("dm-panel-tab", { detail: "shop" })), 100);
    setSelectedCharacter(null);
  };

  const handleBuildRequest = () => {
    socket.emit("requestBuild", selectedCharacter.id);
    setSelectedCharacter(null);
  };

  const handleClose = () => {
    setSelectedCharacter(null);
  };

  return (
    <div className="fixed inset-0 z-[20] flex items-center justify-center">
      {/* Backdrop — click to close */}
      <div className="absolute inset-0 bg-black/30" onClick={handleClose} />

      <div className="relative pointer-events-auto bg-white/95 backdrop-blur-md rounded-2xl border border-gray-200 shadow-2xl min-w-[240px] max-w-[280px] overflow-hidden">
        {/* Avatar thumbnail */}
        <div className="bg-gradient-to-br from-gray-50 to-gray-100 flex items-center justify-center py-5">
          <div className="w-20 h-20 rounded-full overflow-hidden bg-gray-200 border-2 border-gray-300 shadow-lg">
            {!imgError ? (
              <img
                src={thumbnailUrl}
                alt={selectedCharacter.name}
                className="w-full h-full object-cover"
                onError={() => setImgError(true)}
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-gray-400">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                </svg>
              </div>
            )}
          </div>
        </div>

        {/* Name + badge */}
        <div className="text-center px-4 pt-3 pb-2">
          <p className="text-gray-900 font-semibold text-base">{selectedCharacter.name || "Player"}</p>
          <span className={`inline-block mt-1 text-xs font-semibold px-2.5 py-0.5 rounded-full ${
            selectedCharacter.isBot
              ? "bg-blue-100 text-blue-600"
              : "bg-green-100 text-green-600"
          }`}>
            {selectedCharacter.isBot ? "Bot" : "Player"}
          </span>
        </div>

        {/* Actions */}
        <div className="flex flex-col gap-2 p-3 pt-2">
          <button
            onClick={handleWave}
            className="w-full flex items-center gap-2 px-3 py-2 rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm transition-colors text-left"
          >
            <span className="text-base">{"\u{1F44B}"}</span>
            <span>Wave at {selectedCharacter.name || "them"}</span>
          </button>
          <button
            onClick={handleFollow}
            className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm transition-colors text-left ${
              isFollowing
                ? "bg-blue-100 hover:bg-blue-200 text-blue-600"
                : "bg-gray-100 hover:bg-gray-200 text-gray-700"
            }`}
          >
            <span className="text-base">{isFollowing ? "\u{1F441}\uFE0F" : "\u{1F4F7}"}</span>
            <span>{isFollowing ? "Unfollow camera" : `Follow ${selectedCharacter.name || "them"}`}</span>
          </button>
          {selectedCharacter.isBot && (
            <>
              <button
                onClick={handleTalkTo}
                className="w-full flex items-center gap-2 px-3 py-2 rounded-lg bg-indigo-50 hover:bg-indigo-100 text-indigo-700 text-sm transition-colors text-left"
              >
                <span className="text-base">{"\u{1F4AC}"}</span>
                <span>Talk to {selectedCharacter.name || "them"}</span>
              </button>
              <button
                onClick={handleShop}
                className="w-full flex items-center gap-2 px-3 py-2 rounded-lg bg-amber-50 hover:bg-amber-100 text-amber-700 text-sm transition-colors text-left"
              >
                <span className="text-base">{"\u{1F6D2}"}</span>
                <span>Shop</span>
              </button>
              <button
                onClick={handleBuildRequest}
                className="w-full flex items-center gap-2 px-3 py-2 rounded-lg bg-orange-50 hover:bg-orange-100 text-orange-700 text-sm transition-colors text-left"
              >
                <span className="text-base">{"\u{1F528}"}</span>
                <span>Help me build</span>
              </button>
            </>
          )}
        </div>

        {/* Close button */}
        <button
          onClick={handleClose}
          className="absolute top-2 right-2 text-gray-400 hover:text-gray-600 transition-colors w-7 h-7 flex items-center justify-center rounded-full bg-gray-200/50 hover:bg-gray-200"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  );
};

// Preload is handled dynamically per-avatar, no static preload needed
useGLTF.preload("/animations/M_Walk_001.glb");
useGLTF.preload("/animations/M_Standing_Idle_001.glb");
useGLTF.preload("/animations/M_Dances_001.glb");
useGLTF.preload("/animations/M_Standing_Expressions_001.glb");
